services:
  configurator:
    image: jeppeotte/gateway_configurator:latest
    container_name: gateway_configurator
    restart: unless-stopped
    volumes:
      - ./:/mounted_dir:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev:/dev
    environment:
      HOST_PLATFORM: #Add the operating system of the device eg. linux, windows or mac
      HOST_ARCH:  #Add the chip architecture of the device eg. amd64 or arm64
    ports:
      - "8000:8000"
    privileged: true

  valkey:
    image: valkey/valkey
    container_name: messagebus
    restart: unless-stopped
    ports:
      - "6379:6379"
